import glob from 'glob-promise';
import { join, relative } from 'path';
import spaceTrim from 'spacetrim';
import { IWorkflowOptions, WorkflowResult } from '../IWorkflow';

const WALLPAPER_IN_MARKDOWN = /<!--Wallpaper-->(?<wallpaper>.*)<!--\/Wallpaper-->/is;

export async function aiGeneratedWallpaperUseInReadme({
    projectTitle,
    projectName,
    projectPath,
    projectOrg,
    modifyFiles,
    commit,
    skippingBecauseOf,
    mainBranch,
}: IWorkflowOptions): Promise<WorkflowResult> {
    // !!! Dry to some util
    const wallpaperPath = join(projectPath, '/assets/ai/wallpaper/');
    const wallpaperGalleryPath = join(wallpaperPath, 'gallery');

    // TODO: !!! Choose current better than just the first
    const wallpaperCurrentPath = (await glob(join(wallpaperGalleryPath, '*.png')))[0];

    if (!wallpaperCurrentPath) {
        return skippingBecauseOf(`No wallpaper yet`);
    }

    const wallpaperMarkdown = spaceTrim(`
        <!--Wallpaper-->
        <!--⚠️WARNING: This section was generated by https://github.com/hejny/batch-project-editor/blob/main/src//workflows/315-ai-generated-wallpaper/4-aiGeneratedWallpaperUseInReadme.ts so every manual change will be overwritten.-->
        ![Wallpaper of ${projectTitle}](${relative(projectPath, wallpaperCurrentPath).split('\\').join('/')})
        <!--/Wallpaper-->
    `);

    await modifyFiles('README.md', async (readmeContent) => {
        if (WALLPAPER_IN_MARKDOWN.test(readmeContent)) {
            return readmeContent.replace(WALLPAPER_IN_MARKDOWN, wallpaperMarkdown);
        } else {
            let added = false;
            return readmeContent
                .split('\n')
                .map((line) => {
                    if (!added && line.startsWith('#')) {
                        added = true;
                        return `${line}\n\n${wallpaperMarkdown}`;
                    }

                    return line;
                })
                .join('\n');
        }
    });

    return commit('🤖🖼️🌽 Update AI–⁠generated in README');
}
