import glob from 'glob-promise';
import { join, relative } from 'path';
import spaceTrim from 'spacetrim';
import { DESCRIPTION_IN_README } from '../310-description/description';
import { IWorkflowOptions, WorkflowResult } from '../IWorkflow';

export const WALLPAPER_IN_README = /<!--Wallpaper-->(?<wallpaper>.*)<!--\/Wallpaper-->/is;

export async function aiGeneratedWallpaperUseInReadme({
    projectTitle,
    projectName,
    projectPath,
    projectOrg,
    modifyFiles,
    commit,
    skippingBecauseOf,
    mainBranch,
}: IWorkflowOptions): Promise<WorkflowResult> {
    // !!! Dry to some util
    const wallpaperPath = join(projectPath, '/assets/ai/wallpaper/');
    const wallpaperGalleryPath = join(wallpaperPath, 'gallery');

    // TODO: !!! Choose current better than just the first
    const wallpaperCurrentPath = (await glob(join(wallpaperGalleryPath, '*.png')))[0];

    if (!wallpaperCurrentPath) {
        return skippingBecauseOf(`No wallpaper yet`);
    }

    const wallpaperMarkdown = spaceTrim(`
        <!--Wallpaper-->
        <!--⚠️WARNING: This section was generated by https://github.com/hejny/batch-project-editor/blob/main/src//workflows/315-ai-generated-wallpaper/4-aiGeneratedWallpaperUseInReadme.ts so every manual change will be overwritten.-->
        ![Wallpaper of ${projectTitle}](${relative(projectPath, wallpaperCurrentPath).split('\\').join('/')})
        <!--/Wallpaper-->
    `);

    await modifyFiles('README.md', (readmeContent) => {
        if (WALLPAPER_IN_README.test(readmeContent)) {
            return readmeContent.replace(WALLPAPER_IN_README, wallpaperMarkdown);
        } else {
            const descriptionMatch = readmeContent.match(DESCRIPTION_IN_README);

            if (!descriptionMatch) {
                return readmeContent;
            }
            const descriptionSection = descriptionMatch[0];

            return readmeContent.replace(descriptionSection, descriptionSection + '\n\n' + wallpaperMarkdown + `\n\n`);
        }
    });

    return commit('🤖🖼️🌽 Update AI–⁠generated in README');
}

/**
 * TODO: [🎸] Some common util to modify readme
 * TODO: [🏨] Some common config to parse readme - WALLPAPER_IN_README
 */
