import spaceTrim from 'spacetrim';
import { IWorkflowOptions } from '../IWorkflow';

const CONTRIBUTING_IN_MARKDOWN = /<!--Contributing-->(?<badges>.*)<!--\/Contributing-->/is;

export async function contributing({
    projectName,
    projectOrg,
    modifyFiles,
    commit,
    mainBranch,
}: IWorkflowOptions): Promise<void> {
    const contributingMarkdown =
        projectOrg !== 'hejny'
            ? ``
            : spaceTrim(`

                <!--Contributing-->
                <!--⚠️WARNING: This section was generated by https://github.com/hejny/batch-project-editor/blob/main/src/workflows/810-contributing/contributing.ts so every manual change will be overwritten.-->

                ## 🖋️ Contributing

                I am open to pull requests, feedback, and suggestions. Or if you like this utility, you can [☕ buy me a coffee](https://www.buymeacoffee.com/hejny) or [donate via cryptocurrencies](https://github.com/hejny/hejny/blob/main/documents/crypto.md).

                You can also ⭐ star the ${projectName} package, [follow me on GitHub](https://github.com/hejny) or [various other social networks](https://www.pavolhejny.com/contact/).

                <!--/Contributing-->

              `);

    await modifyFiles('README.md', async (readmeContent) => {
        // TODO: Include prettier formatting
        if (CONTRIBUTING_IN_MARKDOWN.test(readmeContent)) {
            return readmeContent.replace(CONTRIBUTING_IN_MARKDOWN, contributingMarkdown);
        } else {
            return spaceTrim(
                (block) => `

                  ${block(readmeContent)}


                  ${block(contributingMarkdown)}

            `,
            );
        }
    });

    await commit('🖋️ Update contributing');
}
