import chalk from 'chalk';
import { execGitCommit } from './execCommand/execGitCommit';
import { isWorkingTreeClean } from './isWorkingTreeClean';

interface ICommitOptions {
    projectPath: string;
    message: string;
}

export async function commit({ projectPath, message }: ICommitOptions): Promise<boolean> {
    if (await isWorkingTreeClean(projectPath)) {
        console.info(chalk.gray(`⏩ Not commiting because nothings changed`));
        return false;
    }

    return await execGitCommit({
        cwd: projectPath,
        messageTitle: message,
        messageDescription:
            '🔼 This commit was automatically generated by [Batch project editor](https://github.com/hejny/batch-project-editor)',

        isAllAdded: true,
        isPushed: true,
    });
}
