import spaceTrim from 'spacetrim';
import { IWorkflowOptions, WorkflowResult } from '../IWorkflow';
import { pickPartnersForProject } from './organizations';

const PARTNERS_IN_README = /<!--Partners-->(?<badges>.*)<!--\/Partners-->/is;

export async function partners({
    projectUrl,
    projectName,
    projectOrg,
    modifyFile,
    commit,
    currentBranch,
}: IWorkflowOptions): Promise<WorkflowResult> {
    const organizations = pickPartnersForProject({
        projectUrl,
        projectOrg,
        projectName,
    });

    const partnersMarkdown =
        organizations.length === 0
            ? ``
            : spaceTrim(
                  (block) => `

                    <!--Partners-->
                    <!--⚠️WARNING: This section was generated by https://github.com/hejny/batch-project-editor/blob/main/src/workflows/820-partners/partners.ts so every manual change will be overwritten.-->

                    ## ✨ Partners


                    ${block(
                        organizations
                            .map(({ title, url, logoLightModeSrc, logoDarkModeSrc, height }) =>
                                // #gh-light-mode-only | height=${height}
                                spaceTrim(`
                                    <a href="${url}" title="${title}"><img src="${logoLightModeSrc}#gh-light-mode-only" alt="${title}" height="${height}"/></a>
                                `),
                            )
                            .join('\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n'),
                    )}


                    [Become a partner](https://www.pavolhejny.com/contact/)

                    <!--/Partners-->

                `,
              );

    await modifyFile('README.md', async (readmeContent) => {
        if (readmeContent === null) {
            return null;
        }
        if (PARTNERS_IN_README.test(readmeContent)) {
            return readmeContent.replace(PARTNERS_IN_README, partnersMarkdown);
        } else {
            return spaceTrim(
                (block) => `

                  ${block(readmeContent)}


                  ${block(partnersMarkdown)}

            `,
            );
        }
    });

    return commit('✨ Update partners');
}

/**
 * TODO: [🎸] Some common util to modify readme
 * TODO: [🏨] Some common config to parse readme - PARTNERS_IN_README
 */
